Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  k3s_token = "42_iot_secret_token"

  # ==========================================
  # VM 1: Controller / Server (msacaliuS)
  # ==========================================
  config.vm.define "msacaliuS" do |server|
    server.vm.hostname = "msacaliuS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider :libvirt do |v|
      v.cpus = 1
      v.memory = 512
    end
    # // fall back for vb
    # server.vm.provider :virtualbox do |v|
    #   v.cpus = 1
    #   v.memory = 512
    # end

    server.vm.provision "shell", inline: <<-SHELL
      # get primary clusetr network
      IFACE=$(ip -o -4 addr show | grep '192.168.56.' | awk '{print $2}')

      # Installing K3s Controller
      curl -sfL https://get.k3s.io | K3S_TOKEN="#{k3s_token}" INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=$IFACE --write-kubeconfig-mode=644" sh -s - server
      # // add allias for kubecrl
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc
      echo "alias k='kubectl'" >> /root/.bashrc
    SHELL
  end

  # ==========================================
  # VM 2: Worker / Agent (msacaliuSW)
  # ==========================================
  config.vm.define "msacaliuSW" do |worker|
    worker.vm.hostname = "msacaliuSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider :libvirt do |v|
      v.cpus = 1
      v.memory = 512
    end

    # worker.vm.provider :virtualbox do |v|
    #   v.cpus = 1
    #   v.memory = 512
    # end

    worker.vm.provision "shell", inline: <<-SHELL
      # Grab ip adress
      IFACE=$(ip -o -4 addr show | grep '192.168.56.' | awk '{print $2}')

      # install k3s worker
      curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" K3S_TOKEN="#{k3s_token}" INSTALL_K3S_EXEC="--node-ip=192.168.56.111 --flannel-iface=$IFACE" sh -s - agent
    SHELL
  end
end

